# Render Blueprint for Pharmacy Dashboard
# This file enables one-click deployment to Render

services:
  # Full-stack Web Service (Frontend + Backend)
  - type: web
    name: pharmacy-dashboard
    env: python
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Install Node.js and build frontend
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo apt-get install -y nodejs
      cd client && npm ci && npm run build && cd ..
    startCommand: python app.py
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        generateValue: true  # Let Render assign the port
      - key: GOOGLE_DRIVE_CSV_URL
        sync: false  # Set this manually in Render dashboard if using Google Drive

  # Frontend Static Site
  - type: web
    name: pharmacy-dashboard-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://pharmacy-dashboard-api.onrender.com

# Optional: Database (if you want to migrate from CSV to database later)
# databases:
#   - name: pharmacy-db
#     plan: free
#     databaseName: pharmacy_dashboard
#     user: pharmacy_user
